const cardData = [
    {
        title: 'ADAMAN AND NICOBAR ISLANDS',
        description:
          "Andaman and Nicobar Islands, a union territory in the Bay of Bengal, boast a unique culture blending indigenous tribes, settlers, and visitors, fostering peaceful coexistence.",
        imageUrl: 'https://st5.depositphotos.com/6318296/67334/v/450/depositphotos_673345656-stock-illustration-gili-islands-indonesia-colorful-vector.jpg',
        foodImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcpNz-RgofgTzMOPfz5f8R_f4Y40--4U0jMGcngZ1bCw&s',
        foodTitle1: 'Fish Curry',
        foodImage2: 'https://www.seriouseats.com/thmb/3dFjzacZ0gSdlibO6UpuBwBeSaw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2014__03__25.03.201420Spicy-Indian-Crab-Masala-Fry-cd7dc3ba0d8b4f3489c13c4989ddeb4c.jpg',
        foodTitle2: 'Crab Masala',
        touristPlacesImage1: 'https://www.trawell.in/admin/images/upload/171363660Andaman_Cellular_Jail_Main.jpg',
        touristTitle1: 'Cellular Jail',
        touristPlacesImage2: 'https://andamantourism.org.in/images/places-to-visit/header/ross-island-andaman-tourism-entry-fee-timings-holidays-reviews-header.jpg',
        touristTitle2: 'Ross Island',
      },
    {
      title: 'ANDHRA PRADESH',
      description:
        "The state is also recognized for its contribution to classical dance forms like Kuchipudi.",
      imageUrl: 'https://cdn.dribbble.com/users/1207323/screenshots/4646181/media/8a0b4e399f0bebc6bec0dc275b8b081f.jpg?resize=800x600&vertical=center',
      foodImage1: 'https://static.wixstatic.com/media/91e241_475faa4fa56341f3878699dde5ab4904~mv2.jpg/v1/fill/w_720,h_480,al_c,q_80,enc_auto/91e241_475faa4fa56341f3878699dde5ab4904~mv2.jpg',
      foodTitle1: 'Rice',
      foodImage2: 'https://www.licious.in/blog/wp-content/uploads/2022/12/Shutterstock_600874184-1-750x750.jpg',
      foodTitle2: 'Gongura Chicken',
      touristPlacesImage1: 'https://www.holidify.com/images/cmsuploads/compressed/shutterstock_11162494701_20200130180527_20200130180558.png',
      touristTitle1: 'Araku Valley',
      touristPlacesImage2: 'https://static.toiimg.com/img/97972409/Master.jpg',
      touristTitle2: 'Tirumala Venkateswara Temple',
    },
    {
        title: 'ARUNACHAL PRADESH',
        description:
          "This northeastern state is not only known for its breathtaking natural beauty but also for its efforts to preserve indigenous cultures and traditions.",
        imageUrl: 'https://cdn.dribbble.com/users/4112114/screenshots/11213291/media/5c4f29bb6812c98523d1e23ef2a535e3.jpg?resize=800x600&vertical=center', 
        foodImage1: 'https://images.herzindagi.info/image/2022/Nov/2.-Bamboo-Shoots.jpg',
        foodTitle1: 'Pika Pila',
        foodImage2: 'https://akm-img-a-in.tosshub.com/sites/visualstory/wp/2023/11/Bamboo_Shoot_Stir_Fry.jpg',
        foodTitle2: 'Bamboo Shoot',
        touristPlacesImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfr-VuVrT5GIEjQtEv_lMBVixRiz__Uo5wpHv8ItpdgEaCQen4j6NePPYM5DwejfuAveA&usqp=CAU',
        touristTitle1: 'Tawang Monastery',
        touristPlacesImage2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtiGeHulL7MIFS-PmixtzwfoC1agysc12qpFVgpTHJduwIZLa6WN-t4bmO_Y6rCp-wMhc&usqp=CAU',
        touristTitle2: 'Ziro Valley',
      },
      {
        title: 'ASSAM',
        description:
          "Assam, renowned for its tea and silk, boasts vibrant festivals and rich biodiversity, home to the one-horned rhinoceros and vibrant cultural expressions.",
        imageUrl: 'https://cdn.dribbble.com/users/5200116/screenshots/14945489/media/cd9743eee2e891ad8cc2360fa5fabf83.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXK0R5PDz2N33_m0AerbKeZ43xiByaG-XZ6PdLcwaKbYqXk7tdc1HfuBp8N3Ja3ElREE0&usqp=CAU',
        foodTitle1: 'Jolpan',
        foodImage2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3tBgMz9fqA4FkesZ1hDXTb1XXoRFoV7c0nhe1nR_bRWU9pclQArh0qrPdVke_cyH6sbc&usqp=CAU',
        foodTitle2: 'Khar',
        touristPlacesImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPGpdKOvZpLBD0ZhTWkLQzCKAmkkFqyOuEAd_ZlAUcGJM1DFD1lsaUQThZMYO_WIYOOQY&usqp=CAU',
        touristTitle1: 'Kaziranga National Park',
        touristPlacesImage2: 'https://static.toiimg.com/photo/64012913.cms',
        touristTitle2: 'Majuli Island',
      },
      {
        title: 'BIHAR',
        description:
          "Bihar, birthplace of Lord Buddha, houses ancient centers of learning like Nalanda and Vikramshila universities. Renowned for Madhubani art and Bihari cuisine.",
        imageUrl: 'https://cdn.dribbble.com/userupload/11469918/file/original-203227504d1398c738a1f1574e5205b2.png?resize=1200x900',
        foodImage1: 'https://www.secondrecipe.com/wp-content/uploads/2019/11/litti-chokha-1.jpg',
        foodTitle1: 'Litti Chokha',
        foodImage2: 'https://www.chefkunalkapur.com/wp-content/uploads/2021/12/OZZ_9225-scaled.jpg?v=1639763212',
        foodTitle2: 'Sattu Paratha',
        touristPlacesImage1: 'https://media-cdn.tripadvisor.com/media/photo-c/1280x250/11/39/d8/f6/20171109-125300-largejpg.jpg',
        touristTitle1: 'Bodh Gaya',
        touristPlacesImage2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA3YRTlN1Z3PuGe_A4oAIK0h-vT1EE2_WDdOBhEA6AVhQeA4f7kxTxkuSlvkmKEWQWXOc&usqp=CAU',
        touristTitle2: 'Vaishali',
      },
      {
        title: 'CHANDIGARH',
        description:
          "Chandigarh, capital of Punjab and a union territory, is a cosmopolitan hub embodying diverse cultures, reflecting a harmonious blend of cultural influences from across India.",
        imageUrl: 'https://cdn.dribbble.com/users/1125116/screenshots/4629253/media/39d9d03901e4c5048074814729b5463a.jpg?resize=800x600&vertical=center',
        foodImage1: 'https://myfoodstory.com/wp-content/uploads/2022/01/Sarson-ka-Saag-3.jpg',
        foodTitle1: 'Sarson ka Saag',
        foodImage2: 'https://zatpatrecipeingujarati.com/wp-content/uploads/2023/02/chole-bhature-banavani-rit-.jpg',
        foodTitle2: 'Chhole Bhature',
        touristPlacesImage1: 'https://img.veenaworld.com/wp-content/uploads/2021/03/Rock-Garden-Chandigarh-scaled.jpg',
        touristTitle1: 'Rock Garden',
        touristPlacesImage2: 'https://map.sahapedia.org/admin/assets/images/2022051914272928Copy_of_Copy_of_IMG_1912_Edited.jpg?__imr__=bannerArticle',
        touristTitle2: 'Sukhna Lake',
      },
      {
        title: 'CHHATTISGARH',
        description:
          "Chhattisgarh, India's 'Rice Bowl', boasts a vibrant cultural tapestry with Bastar's tribal art and craft traditions. Its lush forests and waterfalls allure both nature enthusiasts and adventurers.",
        imageUrl: 'https://images.assetsdelivery.com/compings_v2/premiumstock/premiumstock1801/premiumstock180100036.jpg',
        foodImage1: 'https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs42779-021-00103-6/MediaObjects/42779_2021_103_Fig1_HTML.jpg',
        foodTitle1: 'Bhakri',
        foodImage2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfLr32rz4UiCosYkn2HNDvanPBP2Mm0K8AcACoNxToy3lZOZaX7RN1Un0agObqjN5Fb80&usqp=CAU',
        foodTitle2: 'Muthiya',
        touristPlacesImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNKBm8gtWKtZi9Ny15ZmAhmJVVmm5_in-EHpOGDV3MI0cckI6w-fo72Lia9c9-Ht71kJM&usqp=CAU',
        touristTitle1: 'Kanger Valley National Park',
        touristPlacesImage2: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/44/c5/49/chitrakoot-falls.jpg?w=1200&h=1200&s=1',
        touristTitle2: 'Chitrakoot Falls',
      },
      {
        title: 'DADRA & NAGAR HAVELI AND DAMAN % DIU',
        description:
          "Dadra and Nagar Haveli and Daman & Diu, a union territory in Western India, comprises Dadra, Nagar Haveli, Daman, and Diu.",
        imageUrl: 'https://thumbs.dreamstime.com/b/vector-diu-india-illustration-beautiful-portuguese-church-postcard-hand-drawn-cityscape-sketch-travel-art-vintage-artistic-234580688.jpg',
        foodImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ73SYbitRMasoAPPNg_RXUMvBijX1orfE0AZmMsUUHNw&s',
        foodTitle1: 'Daman Fish Fry',
        foodImage2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzm9buXZTJ898AgCZwhfiQQsSycVOJnHBUYZ9rlc8UTQ&s',
        foodTitle2: 'Chicken Xacuti',
        touristPlacesImage1: 'https://cdn.britannica.com/27/1627-050-6E7FEBFB/fort-Portuguese-coast-Diu.jpg',
        touristTitle1: 'Daman Fort',
        touristPlacesImage2: 'https://clubmahindra.gumlet.io/blog/media/section_images/bannerdesk-239e5b22c851bd7.webp?w=376&dpr=2.6',
        touristTitle2: 'Nagar Haveli Waterfalls',
      },
      {
        title: 'GOA',
        description:
          "Goa's colonial legacy and picturesque beaches attract tourists, complemented by a vibrant nightlife. Its cuisine, a blend of Portuguese and Konkani.",
        imageUrl: 'https://cdn.dribbble.com/users/6808378/screenshots/15354630/media/fce51dcfa286f06cb718e006640f47a3.jpeg?resize=1000x750&vertical=center',
        foodImage1: 'https://www.spiceandlife.com/wp-content/uploads/2023/02/Kerala-Beef-Fry.jpg',
        foodTitle1: 'Beef Fry',
        foodImage2: 'https://www.recipetineats.com/wp-content/uploads/2020/10/Goan-Fish-Curry_6-SQ.jpg',
        foodTitle2: 'Fish Curry',
        touristPlacesImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwDw7altS78fOuw6AIcW8ulOkgnq_58xY0BEdJUukmzQAa1eRSeut28PipS04YIX5_vNQ&usqp=CAU',
        touristTitle1: 'Basilica of Bom Jesus',
        touristPlacesImage2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT306WyJqMsVtXH_v6rt5ZHxBOwZTwzskjlftEc66mQO2agE7GEZw9-7I_yUwx_u_qznDc&usqp=CAU',
        touristTitle2: 'Palolem Beach',
      },
      {
        title: 'GUJARAT',
        description:
          "Gujarat offers rich heritage and attractions like Kutch desert and Gir National Park, complemented by architectural marvels and the vibrant Rann Utsav, promising travelers an unforgettable cultural experience.",
        imageUrl: 'https://cdn.dribbble.com/users/3421954/screenshots/6276701/gujarat_final_4x.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://i0.wp.com/aartimadan.com/wp-content/uploads/2023/02/Corn-Dhokla.jpg?fit=800%2C449&ssl=1',
        foodTitle1: 'Dhokla',
        foodImage2: 'https://i0.wp.com/myvegetarianroots.com/wp-content/uploads/2019/12/DSC_0024-2.jpeg?fit=1920%2C1335&ssl=1',
        foodTitle2: 'Thepla',
        touristPlacesImage1: 'https://miro.medium.com/v2/resize:fit:840/1*f9tAxE83-Fnc_U2QsWFYgQ.jpeg',
        touristTitle1: 'Gir National Park',
        touristPlacesImage2: 'https://www.tripsavvy.com/thmb/Yh7C0nh6CKbB5BmhRz3il-V8sm8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-537000923-541774dbe2d44759815fdf0719b04685.jpg',
        touristTitle2: 'Rann of Kutch',
      },
      {
        title: 'HARYANA',
        description:
          "Haryana's agrarian economy and Kurukshetra's historical sites underscore its rich cultural heritage, with folk music echoing rural traditions and modern cities driving industrial growth.",
        imageUrl: 'https://cdn.dribbble.com/users/1197681/screenshots/4729204/media/9fcddaae94df9a363cb4dd5510131646.png?resize=800x600&vertical=center',
        foodImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1rNkBmngdcv-BLZN8BSquSQZm_mHkOxhzco7hZrXb4EIn507PjgLTeh_32mHCE2nkvhI&usqp=CAU',
        foodTitle1: 'Parathas',
        foodImage2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGrzSt9MRTWdbMEqWMnCeoVsD7z3UCl7W9OD85GAt3wpMmfCDXb85T5TESY_rfygZad1U&usqp=CAU',
        foodTitle2: 'Kadhi',
        touristPlacesImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWjZLTu-hmUjytgwgnJ6SPGZzqC5XtyICGuS3Ew4z_ZzYCjvP8yo_PK_Eh6XfUBp25e3o&usqp=CAU',
        touristTitle1: 'Taj Mahal',
        touristPlacesImage2: 'https://static.toiimg.com/thumb/50481522/Main-Image-Kurukshetra_compressed.jpg?width=1200&height=900',
        touristTitle2: 'Kurukshetra',
      },
      {
        title: 'HIMACHAL PRADESH',
        description:
          "Himachal Pradesh's scenic allure and adventure sports draw global tourists, while Tibetan influence in Dharamshala and McLeodGanj enriches its cultural tapestry.",
        imageUrl: 'https://cdn.dribbble.com/users/11987547/screenshots/18406630/media/913f45cd103355f8093fa5e94d0f0c3b.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSy7WOHrwscM_EVHKxcGzDSMgBnV6uoN2LPcjmKBNes5yZhPDzKi-DhObejty6jLv6gCg&usqp=CAU',
        foodTitle1: 'Dhaam',
        foodImage2: 'https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Pooja_Thakur/Himachali_Chana_MadraChickpeas_in_yogurt_based_gravy.jpg',
        foodTitle2: 'Madra',
        touristPlacesImage1: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Manali_City.jpg/1200px-Manali_City.jpg',
        touristTitle1: 'Manali',
        touristPlacesImage2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnUV4kip7vpQdfkdRzXSE4VinCv-TuRR3XioGRLEX4rt-Fd9TQKe4p9qOYn5PyXeSwF9s&usqp=CAU',
        touristTitle2: 'Dharamsala',
      },
      {
        title: 'JAMMU & KASHMIR',
        description:
          "Jammu & Kashmir, the 'Paradise on Earth', captivates with breathtaking landscapes, serene lakes, and snow-capped peaks, offering an enchanting escape into nature's embrace.",
        imageUrl: 'https://cdn.dribbble.com/users/5536680/screenshots/12125582/media/f0ef7d2522f615a3dcdf6209ed9cd159.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://www.whiskaffair.com/wp-content/uploads/2019/02/Mutton-Rogan-Josh-2-3.jpg',
        foodTitle1: 'Rogan Josh',
        foodImage2: 'https://i.ytimg.com/vi/QVNtL1bmkcA/maxresdefault.jpg',
        foodTitle2: 'Rajma Kulcha',
        touristPlacesImage1: 'https://static.wanderon.in/wp-content/uploads/2023/11/gondola-ride-in-autumn-in-kashmir-2023-11-03t164430.753-min.png',
        touristTitle1: 'Dal Lake',
        touristPlacesImage2: 'https://www.hindustantimes.com/ht-img/img/2023/05/19/1600x900/Gulmarg_Kashmir_Valley_1684489094985_1684489103602.jpg',
        touristTitle2: 'Gulmarg',
      },
      {
        title: 'JHARKHAND',
        description:
          "Jharkhand's mineral wealth fuels India's industry, complemented by vibrant tribal festivals and natural beauty comprising lush forests and wildlife sanctuaries.",
        imageUrl: 'https://cdn.dribbble.com/users/2420199/screenshots/7475401/media/5c0feeba282dbeb6b7bc5c095b7b3de1.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://www.spicingyourlife.com/wp-content/uploads/2014/04/Jharkhand-Daal-Pitha-Tomata-Chutney.jpg',
        foodTitle1: 'Pitha',
        foodImage2: 'https://i.ytimg.com/vi/FDAKn1v3q-w/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLC7jCdkFgLuQ1adY9VkNAKy6YETlg',
        foodTitle2: 'Kadhi',
        touristPlacesImage1: 'https://1.bp.blogspot.com/-uSijFIYUips/XefqYGO7k8I/AAAAAAAAKe4/whQiKqH1jjgZvoGMS1M6Gim1BoJcMCV_gCLcBGAsYHQ/s1600/IMG-20191203-WA0077.jpg',
        touristTitle1: 'Rajrappa Waterfalls',
        touristPlacesImage2: 'https://travelsetu.com/apps/uploads/new_destinations_photos/destination/2024/01/08/9b09e4f561e8dd2954b42774ecb0bae8_1000x1000.jpg',
        touristTitle2: 'Parasnath Hill',
      },
      {
        title: 'KARNATAKA',
        description:
          "Karnataka's architectural marvels and cultural richness, from Mysore Palace to Bharatanatyam, highlight its heritage amidst IT prowess.",
        imageUrl: 'https://cdn.dribbble.com/users/1118956/screenshots/7163830/media/3ad88d65c05f9631f22125fa9bc7584f.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8CgrvC5qnaBel-n1BxlYG_Sw2S6t3i3236w2jxSX7bg&s',
        foodTitle1: 'Dosa',
        foodImage2: 'https://www.karnataka.com/wp-content/uploads/2018/04/breakfast-2408818_640.jpg',
        foodTitle2: 'Idli',
        touristPlacesImage1: 'https://www.holidify.com/images/cmsuploads/compressed/attr_1568_20191102174918.jpg',
        touristTitle1: 'Mysore Palace',
        touristPlacesImage2: 'https://karnatakatourism.org/wp-content/uploads/2020/05/Hampi.jpg',
        touristTitle2: 'Hampi',
      },
      {
        title: 'KERALA',
        description:
          "Kerala's serene backwaters and Ayurvedic retreats, coupled with Kathakali performances and flavorful cuisine, define its tourist allure and cultural essence.",
        imageUrl: 'https://cdn.dribbble.com/users/11987547/screenshots/18395225/media/9706e97377905aeb371837a62f7339e1.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBrwQv8i7uZdeaWW5uHk_AXchAQxNAdl3_oADNMg1ZjQ&s',
        foodTitle1: 'Sadya',
        foodImage2: 'https://i0.wp.com/foodiesroof.com/wp-content/uploads/2023/04/InShot_20230313_144544740.jpg?w=1170&ssl=1',
        foodTitle2: 'Appam',
        touristPlacesImage1: 'https://www.tripsavvy.com/thmb/UoylMLyzOBPdDp34ForEiJd9m3s=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-522478216-5ab12c4e3de4230036949cee.jpg',
        touristTitle1: 'Backwaters',
        touristPlacesImage2: 'https://deih43ym53wif.cloudfront.net/munnar-kerala-india-shutterstock_108346949_1f8da1cae0.jpeg',
        touristTitle2: 'Munnar',
      },
      {
        title: 'LADAKH',
        description:
          "Ladakh, 'The Land of High Passes', famed for dramatic landscapes and vibrant culture, hosts pristine lakes and ancient monasteries, inviting a mesmerizing Himalayan journey.",
        imageUrl: 'https://cdn.dribbble.com/userupload/12721306/file/original-d61de42a547200caf6729bdcc135c9a9.jpg?resize=1024x1024',
        foodImage1: 'https://images.slurrp.com/prodarticles/jqfj17e4go.webp',
        foodTitle1: 'Skyu',
        foodImage2: 'https://www.lehladakhindia.com/blog/wp-content/uploads/2013/10/Tigmo_in_Leh-Ladakh.jpg',
        foodTitle2: 'Tingmo',
        touristPlacesImage1: 'https://www.kashmirtourmart.com/wp-content/uploads/2020/07/pangong-tso-lake-15.jpeg',
        touristTitle1: 'Pangong Lake',
        touristPlacesImage2: 'https://static.toiimg.com/photo/msid-98905858,width-96,height-65.cms',
        touristTitle2: 'Nubra Valley',
      },
      {
        title: 'LAKSHADWEEP',
        description:
          "Lakshadweep, a tropical paradise in the Arabian Sea, boasts stunning coral islands with pristine beaches and vibrant marine life, offering an idyllic escape into nature's lap.",
        imageUrl: 'https://cdn.dribbble.com/userupload/5055022/file/original-f4855e61ff101c6f77afbd87aef95811.jpg?resize=1024x699&vertical=center',
        foodImage1: 'https://clubmahindra.gumlet.io/blog/images/Kulukki-Sarbath-resized.jpg?w=800&dpr=1.3',
        foodTitle1: 'Kulukki Sarbath',
        foodImage2: 'https://clubmahindra.gumlet.io/blog/images/Mus-Kavaab-resized.jpg?w=800&dpr=1.3',
        foodTitle2: 'Mus Kavaab',
        touristPlacesImage1: 'https://media2.thrillophilia.com/images/photos/000/359/275/original/1603547546_lakshadweep-tour.jpg?width=1600&height=775',
        touristTitle1: 'Agatti Island',
        touristPlacesImage2: 'https://d27k8xmh3cuzik.cloudfront.net/wp-content/uploads/2018/06/view-of-the-gorgeous-Kadmat-Island-OG-ss11052018.jpg',
        touristTitle2: 'Kadmat Island',
      },
      {
        title: 'MADHYA PRADESH',
        description:
          "Madhya Pradesh, the 'Heart of India', boasts historical sites and wildlife sanctuaries, offering safari adventures and diverse cuisine experiences.",
        imageUrl: 'https://cdn.dribbble.com/users/1024227/screenshots/3463801/media/263a950168422979bbf550c4cd8ba4d9.png?resize=800x600&vertical=center',
        foodImage1: 'https://www.chefkunalkapur.com/wp-content/uploads/2022/02/indori-poha-1300x926.jpg?v=1643978014',
        foodTitle1: 'Poha',
        foodImage2: 'https://www.secondrecipe.com/wp-content/uploads/2020/11/dal-bati-churma.jpg',
        foodTitle2: 'Dal Baati Churma',
        touristPlacesImage1: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Khajuraho_Group_of_Monuments_4.jpg/1200px-Khajuraho_Group_of_Monuments_4.jpg',
        touristTitle1: 'Khajuraho Group of Monuments',
        touristPlacesImage2: 'https://www.mptourism.com/images/point-of-interest/The%20Great%20Stupa.jpg',
        touristTitle2: 'Sanchi Stupa',
      },
      {
        title: 'MAHARASHTRA',
        description:
          "Maharashtra's Mumbai shines as India's financial and entertainment hub, Pune as an educational center, while festivals and culinary delights enrich its cultural mosaic.",
        imageUrl: 'https://cdn.dribbble.com/users/605926/screenshots/4375841/media/b328e8c2fd61ab37e7569e66be0ed585.png?resize=800x600&vertical=center',
        foodImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqMniisAGfoYXttFWRWlYMJQc3_FsE5MreOQvXoB2N0Q&s',
        foodTitle1: 'Vada Pav',
        foodImage2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRy43WNvlqdmzV9hoA4YBnSaP3FpzKlP-4SsOUrcAKUKg&s',
        foodTitle2: 'Misal Pav',
        touristPlacesImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQavdLzJRKy3T-JNbsu1m_Vmo7KEQSibYkMANssHS5PHg&s',
        touristTitle1: 'Ajanta and Ellora Caves',
        touristPlacesImage2: 'https://www.fabhotels.com/blog/wp-content/uploads/2019/03/Pratapgarh-Fort.jpg',
        touristTitle2: 'Mahabaleshwar',
      },
  ];