const cardData = [
    {
        title: 'MANIPUR',
        description:
            'Manipur, nestled in Indias northeast, dazzles with its natural beauty and vibrant cultural heritage, including traditional dances like Manipuri dance.',
        imageUrl: 'https://cdn.dribbble.com/users/2484450/screenshots/13973391/media/f6877bbef244a801efb307b04587268b.jpg?resize=800x600&vertical=center',
        foodImage1: 'https://www.shutterstock.com/image-photo/chamthong-manipur-delicious-vegetable-stew-600nw-1367390480.jpg',
        foodTitle1: 'Chamthong ',
        foodImage2: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Ngari-fish.png',
        foodTitle2: 'Ngari',
        touristPlacesImage1: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/a8/08/e3/dzuko-valley-trip-2019.jpg?w=1200&h=-1&s=1',
        touristTitle1: 'Dzukou Valley',
        touristPlacesImage2: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/4e/f8/23/war-cemetery.jpg?w=1200&h=-1&s=1',
        touristTitle2: 'Imphal War Cemetery',
    },
    {
        title: 'MEGHALAYA',
        description:
            'Meghalaya, draped in misty landscapes and lush greenery, enthralls visitors with its breathtaking natural beauty and cascading waterfalls.',
        imageUrl: 'https://cdn.dribbble.com/users/2531449/screenshots/14263748/media/3639a7eb64df03a2b48bf55462c48a74.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://img.onmanorama.com/content/dam/mm/en/food/around-the-world/images/2018/9/16/jadoh.jpg',
        foodTitle1: 'Jadoh',
        foodImage2: 'https://i0.wp.com/www.tusktravel.com/blog/wp-content/uploads/2021/03/Sakin-Gata-Meghalaya.jpg?resize=1200%2C628&ssl=1',
        foodTitle2: 'Sakin Gata',
        touristPlacesImage1: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/b3/91/22/amazing-umium-lake.jpg?w=1200&h=-1&s=1',
        touristTitle1: 'Umiam Lake',
        touristPlacesImage2: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/1d/8a/ce/memories-for-life.jpg?w=1200&h=-1&s=1',
        touristTitle2: 'Elephant Falls',
    },
    {
        title: 'MIZORAM',
        description:
            'Nestled amidst rolling hills and verdant forests, Mizoram beckons with its pristine landscapes and vibrant culture.',
        imageUrl: 'https://images.meesho.com/images/products/197374465/6vkvg_512.webp',
        foodImage1: 'https://rootsandleisure.com/wp-content/uploads/2019/07/1-2.jpg',
        foodTitle1: 'Bai',
        foodImage2: 'https://untolddelicacy.com/wp-content/uploads/2021/08/misa-mach-poora-grilled-shrimp-mizoram.jpg',
        foodTitle2: 'Misa Mach Poora',
        touristPlacesImage1: 'https://bharatkasafar.files.wordpress.com/2014/03/vantawng-falls-mizoram.jpeg',
        touristTitle1: 'Vantawng Falls',
        touristPlacesImage2: 'https://ogapis.ourguest.in/storage/uploads/tours/81/itinerary/7Yhbx29x9BUcAPg6N724WCaUtrJOm4D8FE3XVGKO.jpg',
        touristTitle2: 'Rejek Tlang',
    },
    {
        title: 'NAGALAND',
        description:
            'Nagaland, nestled in the rugged hills of Northeast India, entices travelers with its rich tribal culture and stunning landscapes.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3-OmIsaU61UsRJt478awxjdSTZ94I5Qx4TICCqaFblg&s',
        foodImage1: 'https://1.bp.blogspot.com/-vY4XPulbVlI/VmJziZ2yBlI/AAAAAAAABTk/yko1RPSCHEg/s1600/DSC_0452.JPG',
        foodTitle1: 'Smoked Pork and Bamboo Shoot',
        foodImage2: 'https://images.indianexpress.com/2019/08/axone_759.jpg',
        foodTitle2: 'Axone',
        touristPlacesImage1: 'https://tourism.nagaland.gov.in/wp-content/uploads/2022/06/khonoma-960x600-1.jpg',
        touristTitle1: 'Khonoma Village',
        touristPlacesImage2: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/18/de/d6/kohima-war-cemetery.jpg?w=1200&h=-1&s=1',
        touristTitle2: 'Kohima War Cemetery',
    },
    {
        title: 'ODISHA',
        description:
            'Odisha, nestled along the eastern coast of India, captivates travelers with its rich history, vibrant culture, and diverse landscapes.',
        imageUrl: 'https://cdn.dribbble.com/users/10077658/screenshots/17501379/media/a547f5361a0a1e19148a89ca642d8825.jpg?resize=800x600&vertical=center',
        foodImage1: 'https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Shaheen_Ali/Oriya_Special_Dalma_Recipe_Oriya_Dal_and_Tarkari-1.jpg',
        foodTitle1: 'Dalma',
        foodImage2: 'https://gayathriscookspot.com/wp-content/uploads/2012/04/Chenna-Poda-6-500x500.jpg',
        foodTitle2: 'Chhena Poda',
        touristPlacesImage1: 'https://vajiram-prod.s3.ap-south-1.amazonaws.com/Konark_Sun_Temple_13e71cbb6e.jpg',
        touristTitle1: 'Konark Sun Temple',
        touristPlacesImage2: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Birds_eyeview_of_Chilika_Lake.jpg/800px-Birds_eyeview_of_Chilika_Lake.jpg',
        touristTitle2: 'Chilika Lake',
    },
    {
        title: 'PUDUCHERRY',
        description:
            'Puducherry, also known as Pondicherry, is a charming coastal union territory on the southeastern coast of India, renowned for its French colonial architecture, tranquil beaches, and spiritual ambience.',
        imageUrl: 'https://static.vecteezy.com/system/resources/previews/008/134/259/non_2x/bangkok-thailand-attraction-landmarks-free-vector.jpg',
        foodImage1: 'https://resortinpondicherry.in/wp-content/uploads/2023/03/crab-masala-fry-food.jpg',
        foodTitle1: 'Crab Masala Fry',
        foodImage2: 'https://resortinpondicherry.in/wp-content/uploads/2023/03/ratatouille-food.jpg',
        foodTitle2: 'Ratatouille',
        touristPlacesImage1: 'https://cdnuploads.aa.com.tr/uploads/Contents/2019/02/20/thumbs_b_c_399ee10abc873367a4fe9fe6c1627b3e.jpg?v=123056',
        touristTitle1: 'Auroville',
        touristPlacesImage2: 'https://www.luxurytrailsofindia.com/wp-content/uploads/2016/11/Paradise-Beach-Pondicherry-Tamil-nadu-India.jpg',
        touristTitle2: 'Paradise Beach',
    },
    {
        title: 'PUNJAB',
        description:
            'Punjab, known as the "Land of Five Rivers," beckons with its rich cultural heritage, vibrant festivals, and warm hospitality.',
        imageUrl: 'https://cdn.dribbble.com/users/12757429/screenshots/19060448/media/560f13bf889277154f751bf7824a5012.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://www.bigbasket.com/media/uploads/recipe/w-l/1826_1_1.jpg',
        foodTitle1: 'Sarson ka Saag and Makki Di Roti',
        foodImage2: 'https://niksharmacooks.com/wp-content/uploads/2022/11/ButterChickenDSC_5616.jpg',
        foodTitle2: 'Butter Chicken',
        touristPlacesImage1: 'https://images.thequint.com/thequint%2F2023-06%2F15654156-c8c8-4337-ba19-2e413700c445%2FFyRA7fhaYAIbnGc.jfif?auto=format%2Ccompress&fmt=webp&width=120&w=1200',
        touristTitle1: 'Golden Temple',
        touristPlacesImage2: 'https://amritsartourism.org.in/images/places-to-visit/headers/wagah-border-amritsar-tourism-entry-fee-timings-holidays-reviews-header.jpg',
        touristTitle2: 'Wagah Border',
    },
    {
        title: 'RAJASTHAN',
        description:
            'Rajasthan, the epitome of royal grandeur and vibrant culture, enthralls visitors with its majestic forts, opulent palaces, and colorful traditions.',
        imageUrl: 'https://cdn.dribbble.com/userupload/9322633/file/original-176a4a48688691aab32ec89dd09771b4.jpg?resize=1200x800',
        foodImage1: 'https://www.sharmispassions.com/wp-content/uploads/2015/07/19729847952_b5cc81291a_o.jpg',
        foodTitle1: 'Dal Baati Churma',
        foodImage2: 'https://manjulaskitchen.com/wp-content/uploads/gatte_ki_sabji.jpg',
        foodTitle2: 'Gatte ki Sabji',
        touristPlacesImage1: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/99/ae/7f/images-14-largejpg.jpg?w=700&h=-1&s=1',
        touristTitle1: 'Meherangarh Fort',
        touristPlacesImage2: 'https://s3.india.com/travel/wp-content/uploads/Rajasthan_Pushkar_Pushkar-in-Rajasthan.jpg',
        touristTitle2: 'Pushkar',
    },
    {
        title: 'SIKKIM',
        description:
            'Sikkim, nestled in the lap of the Himalayas, is a land of breathtaking landscapes, vibrant culture, and spiritual sanctuaries.',
        imageUrl: 'https://cdn.dribbble.com/users/975367/screenshots/3628503/media/d8088d761e0facc23de7fe9c5fbfe454.jpg?resize=800x600&vertical=center',
        foodImage1: 'https://www.thespruceeats.com/thmb/UnVh_-znw7ikMUciZIx5sNqBtTU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/steamed-momos-wontons-1957616-hero-01-1c59e22bad0347daa8f0dfe12894bc3c.jpg',
        foodTitle1: 'Momos',
        foodImage2: 'https://www.mapsofindia.com/ci-moi-images/my-india/2014/09/Thupka.jpg',
        foodTitle2: 'Thukpa',
        touristPlacesImage1: 'https://pyt-blogs.imgix.net/2020/05/kinshuk-bose-oXHCpSjWSqs-unsplash-1-scaled.jpg?auto=format&ixlib=php-3.3.0',
        touristTitle1: 'Rumtek Monastery',
        touristPlacesImage2: 'https://static2.tripoto.com/media/filter/tst/img/1241614/TripDocument/1671365719_1671271742381_1_01.jpeg',
        touristTitle2: 'Gurudongmar Lake',
    },
    {
        title: 'TAMIL NADU',
        description:
            'Tamil Nadu, a land of ancient temples, rich history, and vibrant culture, beckons with its diverse landscapes and culinary delights.',
        imageUrl: 'https://cdn.dribbble.com/users/5118725/screenshots/16752916/media/e495530c08d0c59ad4a601965ced0fe1.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://inemai.com/wp-content/uploads/2019/02/Dosai.png',
        foodTitle1: 'Dosai',
        foodImage2: 'https://sidapur.com/cdn/shop/products/Edit_DSC_0033_88b88cbb-06c3-4526-a888-0f441dbcb37d_1100x.jpg?v=1636284130',
        foodTitle2: 'Filter Coffee',
        touristPlacesImage1: 'https://www.savaari.com/blog/wp-content/uploads/2023/11/image-52.png',
        touristTitle1: 'Meenakshi Amman Temple',
        touristPlacesImage2: 'https://c.ndtvimg.com/gws/832/assets/1.jpeg?1597911947',
        touristTitle2: 'Mahabalipuram',
    },
    {
        title: 'TELANGANA',
        description:
            'Telangana, a land steeped in history and culture, offers a blend of ancient heritage and modern innovation.',
        imageUrl: 'https://cdn.dribbble.com/users/1531199/screenshots/11446888/media/6489273115ce23db4e39ec9473b4f861.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://images.firstpost.com/wp-content/uploads/2017/04/chicken-biryani_final1.jpg?im=FitAndFill=(596,336)',
        foodTitle1: 'Hyderabadi Biryani',
        foodImage2: 'https://www.vegrecipesofindia.com/wp-content/uploads/2018/02/mirchi-bajji-recipe-1a.jpg',
        foodTitle2: 'Mirchi Bajji',
        touristPlacesImage1: 'https://www.savaari.com/blog/wp-content/uploads/2022/10/Golkonda-fort.jpg',
        touristTitle1: 'Golconda Fort',
        touristPlacesImage2: 'https://media.istockphoto.com/id/1215274990/photo/high-wide-angle-view-of-charminar-in-the-night.jpg?s=612x612&w=0&k=20&c=byyIjqgbslf-L191n6SJu0s35fvNoVeWsxV5rIPK7Sk=',
        touristTitle2: 'Charminar',
    },
    {
        title: 'THE GOVERNMENT OF NCT OF DELHI',
        description:
            'The Government of the National Capital Territory of Delhi (NCT) is the governing body of Delhi, the capital city of India. Delhi is a federal territory and not a union territory.',
        imageUrl: 'https://cdn.dribbble.com/userupload/6550854/file/original-22bca533108ed135096a81c5acd84ddb.jpg?resize=1200x1200',
        foodImage1: 'https://masalaandchai.com/wp-content/uploads/2022/03/Butter-Chicken.jpg',
        foodTitle1: 'Butter Chicken',
        foodImage2: 'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2022/11/22120901/best-paratha-in-Delhi-1.jpg',
        touristPlacesImage1: 'https://static.toiimg.com/photo/65666850.cms',
        touristTitle1: 'Red Fort',
        touristPlacesImage2: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/b7/1f/31/qutab-minar.jpg?w=1200&h=1200&s=1',
        touristTitle2: 'Qutub Minar',
    },
    {
        title: 'TRIPURA',
        description:
            'Tripura, nestled in the northeastern corner of India, is a land of stunning landscapes, rich cultural heritage, and ancient traditions.',
        imageUrl: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e47755c7-fc58-4164-a94e-805bbb3d7c3b/dd2z9y3-6caf1084-5061-4f9a-9f64-957adec5b232.jpg/v1/fill/w_1024,h_1001,q_75,strp/tripura_skyline_silhouette_by_dipanjan16_dd2z9y3-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTAwMSIsInBhdGgiOiJcL2ZcL2U0Nzc1NWM3LWZjNTgtNDE2NC1hOTRlLTgwNWJiYjNkN2MzYlwvZGQyejl5My02Y2FmMTA4NC01MDYxLTRmOWEtOWY2NC05NTdhZGVjNWIyMzIuanBnIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.5eG6PpITidV1kklcur4nhzM4eoBaP3sShGgaaWAHAuo',
        foodImage1: 'https://i.ytimg.com/vi/muXGooBLOkU/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBvbn_z-oW3EKeQP946Seym-LLgeQ',
        foodTitle1: 'Muya Awandru',
        foodImage2: 'https://images.slurrp.com/prod/articles/wo5wpphuyik.webp',
        foodTitle2: 'Chakhwi',
        touristPlacesImage1: 'https://static.india.com/wp-content/uploads/2019/01/Neermahal.png?impolicy=Medium_Resize&w=1200&h=800',
        touristTitle1: 'Neermahal',
        touristPlacesImage2: 'https://travelsetu.com/apps/uploads/new_destinations_photos/destination/2024/01/18/cd178d6d1f96d5530b2e85c45dd3e6a9_1000x1000.jpg',
        touristTitle2: 'Unakoti',
    },
    {
        title: 'UTTARAKHAND',
        description:
            'Uttarakhand, nestled in the lap of the Himalayas, is a land of spiritual sanctuaries, pristine landscapes, and adventurous pursuits.',
        imageUrl: 'https://cdn.dribbble.com/users/366745/screenshots/4662356/kedarnath.png?resize=800x600&vertical=center',
        foodImage1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoKRXk6uWIPFtgI9_3US_tIWtkshTg3tPtnKZOlbop6w&s',
        foodTitle1: 'Garhwali Cuisine',
        foodImage2: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Bal_mithai.jpg/300px-Bal_mithai.jpg',
        foodTitle2: 'Bal Mithai',
        touristPlacesImage1: 'https://static.india.com/wp-content/uploads/2018/08/Valley-of-flowers.jpg?impolicy=Medium_Resize&w=1200&h=800',
        touristTitle1: 'Valley of Flowers',
        touristPlacesImage2: 'https://www.hellocorbett.in/wp-content/uploads/2017/12/corbett-national-park.jpg',
        touristTitle2: 'Jim Corbett National Park',
    },
    {
        title: 'UTTAR PRADESH',
        description:
            'Uttar Pradesh, the heartland of India, is a land of vibrant culture, ancient heritage, and religious fervor.',
        imageUrl: 'https://cdn.dribbble.com/users/5107096/screenshots/11442403/media/be3e22d61bb6789de3987031f68d763f.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://i.ndtvimg.com/i/2017-09/kebab_625x350_71504248496.jpg',
        foodTitle1: 'Tunday Kababi',
        foodImage2: 'https://im.hunt.in/cg/Agra/City-Guide/petha.jpg',
        foodTitle2: 'Petha',
        touristPlacesImage1: 'https://www.travelandleisure.com/thmb/wdUcyBQyQ0wUVs4wLahp0iWgZhc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/taj-mahal-agra-india-TAJ0217-9eab8f20d11d4391901867ed1ce222b8.jpg',
        touristTitle1: 'Taj Mahal',
        touristPlacesImage2: 'https://storage.googleapis.com/prune/blog_image/Varansi-2.jpg',
        touristTitle2: 'Varanasi',
    },
    {
        title: 'WEST BENGAL',
        description:
            'West Bengal, known as the "Cultural Capital of India," is a vibrant and diverse state steeped in history, art, and literature.',
        imageUrl: 'https://cdn.dribbble.com/users/1363686/screenshots/14072016/media/255fed9f7b0f10bfa62c7ee9381116a9.jpg?resize=1000x750&vertical=center',
        foodImage1: 'https://bisarga.com/wp-content/uploads/2021/07/Bengali-Rosogolla-Bisarga-Food-Takeways-Food-Takeway-Kolkata-Howrah-Mumbai-Pune.jpg',
        foodTitle1: 'Rosogolla',
        foodImage2: 'https://somethingiscooking.com/wp-content/uploads/2017/01/BengaliFishCurry2.jpg',
        foodTitle2: 'Fish Curry',
        touristPlacesImage1: 'https://www.savaari.com/blog/wp-content/uploads/2023/07/Kolkata-India-Victoria-Memorial1.webp',
        touristTitle1: 'Victoria Memorial',
        touristPlacesImage2: 'https://www.thestatesman.com/wp-content/uploads/2020/07/SUNDERBAN-1.jpg',
        touristTitle2: 'Sunderbans',
    },
    
    // Add more card data as needed
  ];